project:
  type: default

format:
  pdf:
    engine: lualatex
    documentclass: scrartcl
    fontsize: 12pt
    linestretch: 1.2
    number-sections: true
    toc: true
    toc-depth: 2
    code-line-numbers: true
    code-overflow: wrap

    mainfont: "Ubuntu Sans"
    monofont: "Ubuntu Mono"

execute:
  echo: true
  warning: false
  eval: false
